  /// \file EventLoader.hh
/*
 *
 * EventLoader.hh header template generated by fclass
 * Creation date : mar. sept. 24 2013
 *
 * This file is part of XXX libraries.
 * 
 * XXX is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * XXX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with XXX.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author : Et� R�mi
 * @version
 * @copyright
 *
 *
 */


#ifndef EVENTLOADER_HH
#define EVENTLOADER_HH

#include <iostream>
#include <string>
#include <cstdlib>
#include <cmath>
#include <vector>
#include <map>

// lcio includes
#include "EVENT/LCIO.h"
#include "EVENT/LCEvent.h"

// deve includes
#include "ObjectLoader.hh"
#include "EventDisplay.hh"

namespace deve {


	class EventDisplay;

	/*!
	*
	* @brief  EventLoader class
	*
	*/
	class EventLoader {

		public:

			/*!
			*
			* @brief  Default constructor
			*
			*/
			EventLoader();

			/*!
			*
			* @brief  Default destructor
			*
			*/
			virtual ~EventLoader();

			/*!
			 *
			 * @brief Load an event with a given list of object loaders
			 *
			 */
			void loadEvent( EVENT::LCEvent * , std::map<std::string , ObjectLoader *> &objLoaders );


		protected:


	};  // class

}  // namespace 

#endif  //  EVENTLOADER_HH
