  /// \file GeometryLoader.hh
/*
 *
 * GeometryLoader.hh header template generated by fclass
 * Creation date : mar. sept. 24 2013
 *
 * This file is part of XXX libraries.
 * 
 * XXX is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * XXX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with XXX.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author : Eté Rémi
 * @version
 * @copyright
 *
 *
 */


#ifndef GEOMETRYLOADER_HH
#define GEOMETRYLOADER_HH

#include <iostream>
#include <string>
#include <cstdlib>
#include <cmath>
#include <vector>

namespace deve {

/*! 
 * 
 * @brief  GeometryLoader class
 * 
 */ 

class GeometryLoader {

  public:
    /*!
     *
     * @brief  Default constructor 
     *
     */
    GeometryLoader();

    /*!
     *
     * @brief  Default destructor 
     *
     */
    virtual ~GeometryLoader();

  protected:


};  // class 

}  // namespace 

#endif  //  GEOMETRYLOADER_HH
