  /// \file ObjectLoader.hh
/*
 *
 * ObjectLoader.hh header template generated by fclass
 * Creation date : mar. sept. 24 2013
 *
 * This file is part of Deve libraries.
 * 
 * Deve is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * Deve is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Deve.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author : Eté Rémi
 * @version
 * @copyright
 *
 *
 */


#ifndef OBJECTLOADER_HH
#define OBJECTLOADER_HH

#include <iostream>
#include <string>
#include <cstdlib>
#include <cmath>
#include <vector>
#include <stdexcept>
#include <exception>

// lcio includes
#include "EVENT/LCCollection.h"

namespace deve {

	/*!
	*
	* @brief  ObjectLoader class
	*
	*/
	class ObjectLoader {

			public:

			/*!
			*
			* @brief Constructor
			*
			*/
			ObjectLoader( const std::string &objType )
				: objectType( objType ) {}

			/*!
			*
			* @brief Default destructor
			*
			*/
			virtual ~ObjectLoader();

			/*!
			 *
			 * @brief Load the specific objects from a lcio LCCollection pointer and a collection name
			 *
			 */
			virtual void loadObjectsFromLCCollection( EVENT::LCCollection * , const std::string & ) = 0;

			/*!
			 *
			 * @brief Load objects from an other framework.
			 *
			 */
			virtual void loadObjects( void * ) = 0;

			/*!
			 *
			 * @brief Return the object type.
			 *
			 */
			const std::string &getObjectType() { return objectType; }



		protected:

			std::string objectType;    ///< The object type that has to be loaded.




	};  // class

}  // namespace 

#endif  //  OBJECTLOADER_HH
