  /// \file TrackLoader.cc
/*
 *
 * TrackLoader.cc source template generated by fclass
 * Creation date : mar. sept. 24 2013
 *
 * This file is part of XXX libraries.
 * 
 * XXX is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * XXX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with XXX.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author : Et� R�mi
 * @version
 * @copyright
 *
 *
 */


#include "TrackLoader.hh"

namespace deve {

	TrackLoader::~TrackLoader() {

	}

	void TrackLoader::loadObjectsFromLCCollection( EVENT::LCCollection * , const std::string & ) {

	}


	void TrackLoader::loadObjects( void * ) {

		// Nothing to do here. See loadObjectsFromLCCollection(*) method
		return;
	}


}  // namespace 

